### ISSUE TITLE
Typo in  'Help-About.....'

### ISSUE THREAD

**Issue by Barough** [jniemann66/ferocious#2]
Noticed a little typo in the About box
It say 'Converter Vesion' in there, but i think it should say 'Converter Version'. ;)

**Comment by jniemann66** [comment]
Yes indeed. Thanks for that - well spotted! Funny that I must have looked at that 100 times and never noticed it before - and I am fussy about spelling.
I will fix it soon in a new build

**Comment by jniemann66** [comment]
Ok that should be fixed now. Thanks
